USE MAT_APP;
    			ALTER TABLE CLAUSE
					DROP FOREIGN KEY CONTEXT_FK;
				ALTER TABLE CLAUSE
					DROP FOREIGN KEY STATUS_FK;
				ALTER TABLE CLAUSE
					DROP FOREIGN KEY MEASURE_FK;
				ALTER TABLE DECISION
					DROP FOREIGN KEY CLAUSE_FK;
				ALTER TABLE MEASURE
					DROP FOREIGN KEY MEASURE_OWNER_FK;
				ALTER TABLE MEASUREMENT_TERM
					DROP FOREIGN KEY DECISION_FK2;
				ALTER TABLE AUDIT_LOG
					DROP FOREIGN KEY USER_FK2;
      			ALTER TABLE AUDIT_LOG
					DROP FOREIGN KEY USER_FK3;
					
				ALTER TABLE `MAT_APP`.`AUDIT_LOG` CHANGE COLUMN `QDM_ID` `QDS_ID` VARCHAR(32) NULL DEFAULT NULL;
					
