SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE MAT_TRAINING_APP ;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`DECISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`DECISION` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`DECISION` (
  `ID` VARCHAR(64) NOT NULL ,
  `OPERATOR` VARCHAR(45) NOT NULL ,
  `PARENT_ID` VARCHAR(64) ,
  `ORDER_NUM` VARCHAR(32) ,
  `CLAUSE_ID` VARCHAR(64) ,
  `ATTRIBUTE_ID` VARCHAR(64) ,
PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QDSTERM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QDS_TERM` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QDS_TERM` (
  `ID` VARCHAR(64) NOT NULL ,
  `QDS_ELEMENT_ID` VARCHAR(64) NOT NULL ,
  `DECISION_ID` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`ID`))
/*
  INDEX `QDS_ELEMENT_ID_FK1` (`QDS_ELEMENT_ID` ASC),
    INDEX `DECISION_ID_FK1` (`DECISION_ID` ASC),
    
    CONSTRAINT `QDS_ELEMENT_ID_FK1`
    FOREIGN KEY (`QDS_ELEMENT_ID`)
    REFERENCES MAT_TRAINING_APP.`QDS_ELEMENT` (`ID`),
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
    CONSTRAINT `DECISION_ID_FK1`
    FOREIGN KEY (`DECISION_ID` )
    REFERENCES MAT_TRAINING_APP.`DECISION` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
*/    
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`MEASUREMENT_TERM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`MEASUREMENT_TERM` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`MEASUREMENT_TERM` (
  `ID` VARCHAR(64) NOT NULL ,
  `UNIT` VARCHAR(45),
  `QUANTITY` VARCHAR(100) NOT NULL ,
  `DECISION_ID` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`ID`))
  /*
    INDEX `DECISION_ID_FK2` (`DECISION_ID` ASC) ,
    CONSTRAINT `DECISION_ID_FK2`
    FOREIGN KEY (`DECISION_ID` )
    REFERENCES MAT_TRAINING_APP.`DECISION` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE) */
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`OPERATORS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`OPERATORS` ;

/* NOT USING, SINCE ENUMS HOLD OPERATOR INFO
CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`OPERATORS` (
  `ID` VARCHAR(32) NOT NULL ,
  `SYMBOL` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `OPERATOR_TYPE` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;
*/
-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CLAUSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CLAUSE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CLAUSE` (
  `ID` VARCHAR(32) NOT NULL ,
  `NAME` VARCHAR(100),
  `DESCRIPTION` VARCHAR(2000),
  `MEASURE_ID` VARCHAR(64),
  `CONTEXT_ID` VARCHAR(32),
  `DECISION_ID` VARCHAR(64),
  `CLAUSE_TYPE_ID` VARCHAR(32),
  `STATUS_ID` VARCHAR(32),
  `VERSION` VARCHAR(32),
  PRIMARY KEY (`ID`))
/*TODO should have this constraint not clear why this is commented*/
/*  INDEX `MEASURE_ID_FK` (`MEASURE_ID` ASC) ,
  INDEX `DECISION_ID_FK` (`DECISION_ID` ASC) ,
  CONSTRAINT `MEASURE_ID_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
*/
  
/*TODO should not have this constraint*/
/*
    CONSTRAINT `DECISION_ID_FK`
    FOREIGN KEY (`DECISION_ID` )
    REFERENCES MAT_TRAINING_APP.`DECISION` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    */
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`MEASURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`MEASURE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`MEASURE` (
  `ID` VARCHAR(64) NOT NULL ,
  `MEASURE_OWNER_ID` VARCHAR(40) NOT NULL,
  `ABBR_NAME` VARCHAR(45),
  `DESCRIPTION` VARCHAR(2000),
  `VERSION` VARCHAR(32),
  `MEASURE_STATUS` VARCHAR(32),
  `EXPORT_TS` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`),
  INDEX `MEASURE_OWNER_FK` (`MEASURE_OWNER_ID` ASC),
  CONSTRAINT `MEASURE_OWNER_FK`
    FOREIGN KEY (`MEASURE_OWNER_ID` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON UPDATE CASCADE
    ON DELETE CASCADE
    
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`METADATA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`METADATA` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`METADATA` (
  `METADATA_ID` VARCHAR(64) NOT NULL ,
  `NAME` VARCHAR(100) NOT NULL ,
  `VALUE` VARCHAR(30000) NOT NULL ,
  `MEASURE_ID` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`METADATA_ID`) ,
  INDEX `MEASURE_ID_METADATA_FK` (`MEASURE_ID` ASC) ,
  CONSTRAINT `MEASURE_ID_METADATA_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QUALITY_DATA_SET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QUALITY_DATA_SET` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QUALITY_DATA_SET` (
  `QUALITY_DATA_SET_ID` VARCHAR(32) NOT NULL ,
  `DATA_TYPE_ID` VARCHAR(32) NOT NULL ,
  `LIST_OBJECT_ID` VARCHAR(32) NOT NULL ,
  `MEASURE_ID` VARCHAR(32) NOT NULL,
  `VERSION` VARCHAR(32) NOT NULL,
  `OID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`QUALITY_DATA_SET_ID`) ,
  INDEX `QDS_DATA_TYPE_FK` (`DATA_TYPE_ID` ASC) ,
  INDEX `QDS_CODE_LIST_FK` (`LIST_OBJECT_ID` ASC) ,
  CONSTRAINT `QDS_DATA_TYPE_FK`
    FOREIGN KEY (`DATA_TYPE_ID` )
    REFERENCES MAT_TRAINING_APP.`DATA_TYPE` (`DATA_TYPE_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `QDS_CODE_LIST_FK`
    FOREIGN KEY (`LIST_OBJECT_ID` )
    REFERENCES MAT_TRAINING_APP.`LIST_OBJECT` (`LIST_OBJECT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `QDS_MEASURE_ID_FK`
    FOREIGN KEY (`MEASURE_ID`)
    REFERENCES MAT_TRAINING_APP.`MEASURE`  (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QUALITY_DATA_SET_OID_GEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QUALITY_DATA_SET_OID_GEN` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QUALITY_DATA_SET_OID_GEN` (
  `OID_GEN_ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(`OID_GEN_ID`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`SHARE_LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`SHARE_LEVEL` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`SHARE_LEVEL` (
  `SHARE_LEVEL_ID` VARCHAR(32) NOT NULL,
  `DESCRIPTION` VARCHAR(50),
  PRIMARY KEY (`SHARE_LEVEL_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`MEASURE_SHARE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`MEASURE_SHARE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`MEASURE_SHARE` (
  `MEASURE_SHARE_ID` VARCHAR(32) NOT NULL ,
  `MEASURE_ID` VARCHAR(32) NOT NULL ,
  `MEASURE_OWNER_USER_ID` VARCHAR(40) NOT NULL,
  `SHARE_USER_ID` VARCHAR(40) NOT NULL ,
  `SHARE_LEVEL_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`MEASURE_SHARE_ID`),
  INDEX `MEASURE_SHARE_MEASURE_FK` (`MEASURE_ID` ASC),
  INDEX `MEASURE_SHARE_OWNER_FK` (`MEASURE_OWNER_USER_ID` ASC),
  INDEX `MEASURE_SHARE_SHARE_FK` (`SHARE_USER_ID` ASC),
  CONSTRAINT `MEASURE_SHARE_MEASURE_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MEASURE_SHARE_OWNER_FK`
    FOREIGN KEY (`MEASURE_OWNER_USER_ID` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,    
  CONSTRAINT `MEASURE_SHARE_SHARE_FK`
    FOREIGN KEY (`SHARE_USER_ID` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE, 
  CONSTRAINT `MEASURE_SHARE_LEVEL_ID`
    FOREIGN KEY (`SHARE_LEVEL_ID` )
    REFERENCES MAT_TRAINING_APP.`SHARE_LEVEL` (`SHARE_LEVEL_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE   
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`PACKAGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`PACKAGER` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`PACKAGER` (
  `PACKAGER_ID` VARCHAR(32) NOT NULL ,
  `MEASURE_ID` VARCHAR(32) NOT NULL ,
  `CLAUSE_ID` VARCHAR(32) NOT NULL,
  `SEQUENCE` INT NOT NULL,
  PRIMARY KEY (`PACKAGER_ID`),
  INDEX `PACKAGER_MEASURE_FK` (`MEASURE_ID` ASC),
  INDEX `PACKAGER_CLAUSE_FK` (`CLAUSE_ID` ASC),
  CONSTRAINT `PACKAGER_MEASURE_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PACKAGER_CLAUSE_FK`
    FOREIGN KEY (`CLAUSE_ID` )
    REFERENCES MAT_TRAINING_APP.`CLAUSE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QDS_ATTRIBUTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QDS_ATTRIBUTES` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QDS_ATTRIBUTES` (
  `ID` VARCHAR(64) NOT NULL,
  `NAME` VARCHAR(100),
  `DATA_TYPE_ID` VARCHAR(32),
  `QDS_ATTRIBUTE_TYPE` VARCHAR(32),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QDS_ATTRIBUTE_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QDS_ATTRIBUTE_DETAILS` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QDS_ATTRIBUTE_DETAILS` (
  `ID` VARCHAR(64) NOT NULL,
  `DECISION_ID` VARCHAR(64),
  `QDS_ATTRIBUTE_ID` VARCHAR(64),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`MEASURE_EXPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`MEASURE_EXPORT` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`MEASURE_EXPORT` (
  `MEASURE_EXPORT_ID` VARCHAR(64) NOT NULL ,
  `MEASURE_ID` VARCHAR(64) NOT NULL ,
  `SIMPLE_XML` LONGTEXT NOT NULL ,
  PRIMARY KEY (`MEASURE_EXPORT_ID`),
  INDEX `MEASURE_EXPORT_ID_MEASURE_FK` (`MEASURE_ID` ASC) ,
  CONSTRAINT `MEASURE_EXPORT_ID_MEASURE_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
