@startmindmap
caption MAT-169
title Tech Spike - MAT - Create New or Edit CQL library item - CQL Library Editor in CQL Workspace
header
 Tech Spike - MAT - Create New or Edit CQL library item - CQL Library Editor in CQL Workspace
endheader
* Root
** Classes
*** AbstractCQLWorkspacePresenter
**** CQLStandaloneWorkSpacePresenter
**** CQLMeasureWorkSpacePresenter
** View
*** Measure Composer
**** CQL Workspace
***** CQL Library Editor
@endmindmap