export const cqlLibraryName = '#CQLLibraryName_Input'
export const saveAndContinueBtn = '#SaveAndContinueButton_cqlDetail'
export const cancelBtn = '#CancelButton_cqlDetail'
export const modelFHIRRadio = '#gwt-uid-15'
export const modelQDMRadio = '#gwt-uid-16'
