USE MAT_APP;

alter table DECISION 
add constraint DECISION_FK3 
foreign key (PARENT_ID) 
references DECISION (ID);

ALTER TABLE CLAUSE ADD CONSTRAINT UNIQUENAME_PERMEASURE UNIQUE (NAME,MEASURE_ID);

