use MAT_APP_STAGING;
DELETE from CLAUSE where CONTEXT_ID = 3;
UPDATE `CLAUSE`  SET `CONTEXT_ID`='3' WHERE `CONTEXT_ID`='4';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='4' WHERE `CONTEXT_ID`='5';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='5' WHERE `CONTEXT_ID`='6';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='6' WHERE `CONTEXT_ID`='7';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='7' WHERE `CONTEXT_ID`='8';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='8' WHERE `CONTEXT_ID`='9';
UPDATE `CLAUSE`  SET `CONTEXT_ID`='9' WHERE `CONTEXT_ID`='10';

UPDATE `CONTEXT`  SET `DESCRIPTION`='Denominator' WHERE `CONTEXT_ID`='3';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Exclusions' WHERE `CONTEXT_ID`='4';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Exceptions' WHERE `CONTEXT_ID`='5';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Population' WHERE `CONTEXT_ID`='6';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Observation' WHERE `CONTEXT_ID`='7';
UPDATE `CONTEXT`  SET `DESCRIPTION`='User-defined' WHERE `CONTEXT_ID`='8';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Phrase' WHERE `CONTEXT_ID`='9';
DELETE from CONTEXT where CONTEXT_ID = '10';

UPDATE CLAUSE SET NAME = REPLACE(NAME, '_Denominator Exclusions', '_Exclusions');
UPDATE CLAUSE SET NAME = REPLACE(NAME, '_Denominator Exceptions', '_Exceptions');

ALTER TABLE MEASURE DROP FOREIGN KEY MEASURE_SET_FK;
drop table IF EXISTS MEASURE_SET;
alter table MEASURE drop column MEASURE_SET_ID;
alter table MEASURE drop column FINALIZED_DATE;
alter table MEASURE drop column DRAFT;
ALTER TABLE MEASURE drop column VERSION;
ALTER TABLE MEASURE add column VERSION VARCHAR(32) DEFAULT NULL;

DELETE from DATABASECHANGELOG where FILENAME='classpath:/liquibase/deploy_01.00.44_20111031.xml';
DELETE from DATABASECHANGELOG where FILENAME='classpath:/liquibase/deploy_01.00.45_20111031.xml';
DELETE from DATABASECHANGELOG where FILENAME='classpath:/liquibase/deploy_01.00.46_20111101.xml';
DELETE from DATABASECHANGELOG where FILENAME='classpath:/liquibase/deploy_01.00.47_20111103.xml';
DELETE from DATABASECHANGELOG where FILENAME='classpath:/liquibase/deploy_01.00.48_20111109.xml';

commit;