UPDATE `CONTEXT`  SET `DESCRIPTION`='Denominator' WHERE `CONTEXT_ID`='3';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Exclusions' WHERE `CONTEXT_ID`='4';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Exceptions' WHERE `CONTEXT_ID`='5';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Population' WHERE `CONTEXT_ID`='6';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Observation' WHERE `CONTEXT_ID`='7';
UPDATE `CONTEXT`  SET `DESCRIPTION`='User-defined' WHERE `CONTEXT_ID`='8';
UPDATE `CONTEXT`  SET `DESCRIPTION`='Measure Phrase' WHERE `CONTEXT_ID`='9';
DELETE from CONTEXT where CONTEXT_ID = '10';