ALTER TABLE MEASURE DROP FOREIGN KEY MEASURE_SET_FK;
drop table IF EXISTS MEASURE_SET;
alter table MEASURE drop column MEASURE_SET_ID;
alter table MEASURE drop column FINALIZED_DATE;
alter table MEASURE drop column DRAFT;
ALTER TABLE MEASURE DROP VERSION;				
ALTER TABLE MEASURE MODIFY VERSION VARCHAR(32) DEFAULT NULL;

#insert into METADATA 
#NAME = 'Version' OR 
#NAME = 'MeasureId' OR 
#NAME='AvailableDate' OR 
#NAME='SetId';