Hello,

You have been granted access to the Measure Authoring Tool. You can use your HARP Account, ${(harpId)!}, to access the Measure Authoring Tool at ${(url)!}. In addition to your HARP user ID and password, you will be asked for a security code generated by HARP to access the tool. Instructions for how to access the HARP security code are available on the Training & Resources page of the public website.

HARP ID: ${(harpId)!}
Email: ${(userEmail)!}
MAT Environment: ${(url)!}

Thank you.

CONFIDENTIALITY NOTICE: This communication, including any attachments, may contain confidential information and is intended only for the individual or entity to whom it is addressed.  Any review, dissemination, or copying of this communication by anyone other than the intended recipient is strictly prohibited.  If you are not the intended recipient, please notify us immediately by reply email to ${(supportEmailAddress)!} and delete or destroy all copies of the original message and any attachments thereto. Email sent to or from the Measure Authoring Tool or any of its member companies may be retained as required by law or regulation.

