<html>
<head>
	<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
</head>
<body>
<p style="font-family: 'Tahoma'; font-size: 10pt;">You have been granted access to the Measure Authoring Tool. Your can use your HARP ID ${(harpId)!} to access the Measure Authoring Tool at ${(url)!}.
</br></br>
In addition to your MAT user ID and password, you will be asked for a security code generated by Symantec&trade; VIP Access. Instructions for installing Symantec&trade; VIP Access and registering your Symantec&trade; Credential ID with the MAT team is available on the Training & Resources page of the public website. 
</br></br>
HARP ID: ${(harpId)!}
</br>
Email: ${(userEmail)!}
</br>
MAT Environment: ${(url)!}
</br></br>
CONFIDENTIALITY NOTICE: This communication, including any attachments, may contain confidential information and is intended only for the individual or entity to whom it is addressed.  Any review, dissemination, or copying of this communication by anyone other than the intended recipient is strictly prohibited.  If you are not the intended recipient, please notify us immediately by reply email to ${(supportEmailAddress)!} and delete or destroy all copies of the original message and any attachments thereto. Email sent to or from the Measure Authoring Tool or any of its member companies may be retained as required by law or regulation.
</p>
</body>
</html>
