
				CREATE TRIGGER TR_QDM_OID BEFORE INSERT ON QUALITY_DATA_MODEL
				 FOR EACH ROW
				 BEGIN 
				    IF NEW.OID IS NULL THEN
				      INSERT INTO `QUALITY_DATA_MODEL_OID_GEN` values ();
				      SET NEW.OID = (SELECT MAX(OID_GEN_ID) from QUALITY_DATA_MODEL_OID_GEN);
				    END IF;
				 END; 
				 
				 