SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS MAT_TRAINING_APP ;
CREATE SCHEMA IF NOT EXISTS MAT_TRAINING_APP DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE MAT_TRAINING_APP ;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`AUDIT_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`AUDIT_LOG` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`AUDIT_LOG` (
  `AUDIT_LOG_ID` VARCHAR(32) NOT NULL ,
  `CREATE_DATE` TIMESTAMP NOT NULL ,
  `CREATE_USER` VARCHAR(40) NOT NULL ,
  `UPDATE_DATE` TIMESTAMP NULL ,
  `UPDATE_USER` VARCHAR(40) NULL ,
  `ACTIVITY_TYPE` VARCHAR(32) NULL ,
  `MEASURE_ID` VARCHAR(32) NULL ,
  `LIST_OBJECT_ID` VARCHAR(32) NULL ,
  `CLAUSE_ID` VARCHAR(32) NULL ,
  `QDS_ID` VARCHAR(32) NULL ,
  PRIMARY KEY (`AUDIT_LOG_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`SECURITY_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`SECURITY_ROLE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`SECURITY_ROLE` (
  `SECURITY_ROLE_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`SECURITY_ROLE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`STATUS` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`STATUS` (
  `STATUS_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`STATUS_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`USER` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`USER` (
  `USER_ID` VARCHAR(40) NOT NULL ,
  `FIRST_NAME` VARCHAR(100) NOT NULL ,
  `MIDDLE_INITIAL` VARCHAR(45) NULL ,
  `LAST_NAME` VARCHAR(100) NOT NULL ,
  `EMAIL_ADDRESS` VARCHAR(254) NOT NULL ,
  `PHONE_NO` VARCHAR(45) NOT NULL ,
  `TITLE` VARCHAR(45) NULL ,
  `TERMINATION_DATE` DATE NULL ,
  `ACTIVATION_DATE` DATE NOT NULL ,
  `SIGN_IN_DATE` TIMESTAMP NULL ,
  `SIGN_OUT_DATE` TIMESTAMP NULL ,
  `LOCKED_OUT_DATE` TIMESTAMP NULL ,
  `STATUS_ID` VARCHAR(32) NOT NULL ,
  `AUDIT_ID` VARCHAR(32) NOT NULL ,
  `SECURITY_ROLE_ID` VARCHAR(32) NOT NULL ,
  `ORGANIZATION_NAME` VARCHAR(80) NOT NULL ,
  `ORG_OID` VARCHAR(50) NOT NULL ,
  `ROOT_OID` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`USER_ID`) ,
  INDEX `USER_SECURITY_ROLE_FK` (`SECURITY_ROLE_ID` ASC) ,
  INDEX `USER_AUDIT_FK` (`AUDIT_ID` ASC) ,
  INDEX `USER_STATUS_FK` (`STATUS_ID` ASC) ,
  CONSTRAINT `USER_SECURITY_ROLE_FK`
    FOREIGN KEY (`SECURITY_ROLE_ID` )
    REFERENCES MAT_TRAINING_APP.`SECURITY_ROLE` (`SECURITY_ROLE_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `USER_AUDIT_FK`
    FOREIGN KEY (`AUDIT_ID` )
    REFERENCES MAT_TRAINING_APP.`AUDIT_LOG` (`AUDIT_LOG_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `USER_STATUS_FK`
    FOREIGN KEY (`STATUS_ID` )
    REFERENCES MAT_TRAINING_APP.`STATUS` (`STATUS_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`USER_PASSWORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`USER_PASSWORD` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`USER_PASSWORD` (
  `USER_PASSWORD_ID` VARCHAR(32) NOT NULL ,
  `USER_ID` VARCHAR(40) NOT NULL ,
  `PWD_LOCK_COUNTER` INT(11)  NULL ,
  `FORGOT_PWD_LOCK_COUNTER` INT(11)  NULL ,
  `PASSWORD` VARCHAR(100) NOT NULL ,
  `SALT` VARCHAR(100) NOT NULL ,
  `INITIAL_PWD` TINYINT(1)  NULL DEFAULT false ,
  `CREATE_DATE` DATE NOT NULL ,
  `FIRST_FAILED_ATTEMPT_TIME` TIMESTAMP NULL ,
  `TEMP_PWD` TINYINT(1)  NULL DEFAULT false ,
  PRIMARY KEY (`USER_PASSWORD_ID`) ,
  INDEX `PASSWORD_USER_FK` (`USER_ID` ASC) ,
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) ,
  CONSTRAINT `PASSWORD_USER_FK`
    FOREIGN KEY (`USER_ID` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`USER_SECURITY_QUESTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`USER_SECURITY_QUESTIONS` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`USER_SECURITY_QUESTIONS` (
  `USER_ID` VARCHAR(40) NOT NULL ,
  `ROW_ID` INT(11)  NOT NULL ,
  `QUESTION` VARCHAR(100) NOT NULL ,
  `ANSWER` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`USER_ID`, `ROW_ID`) ,
  INDEX `SECURITY_QUES_USER_FK` (`USER_ID` ASC) ,
  CONSTRAINT `SECURITY_QUES_USER_FK`
    FOREIGN KEY (`USER_ID` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`OBJECT_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`OBJECT_STATUS` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`OBJECT_STATUS` (
  `OBJECT_STATUS_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`OBJECT_STATUS_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CATEGORY` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CATEGORY` (
  `CATEGORY_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  `ABBREVIATION` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`CATEGORY_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`MEASURE_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`MEASURE_TYPES` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`MEASURE_TYPES` (
  `ID` VARCHAR(32) NOT NULL ,
  `NAME` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`STEWARD_ORG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`STEWARD_ORG` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`STEWARD_ORG` (
  `ID` VARCHAR(32) NOT NULL ,
  `ORG_NAME` VARCHAR(200) NOT NULL ,
  `ORG_OID` VARCHAR(100) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`AUTHOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`AUTHOR` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`AUTHOR` (
  `ID` VARCHAR(32) NOT NULL ,
  `AUTHOR_NAME` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`DATA_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`DATA_TYPE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`DATA_TYPE` (
  `DATA_TYPE_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  `CATEGORY_ID` VARCHAR(32) NOT NULL ,
  PRIMARY KEY (`DATA_TYPE_ID`) ,
  INDEX `DATA_TYPE_CAT_FK` (`CATEGORY_ID` ASC) ,
  CONSTRAINT `DATA_TYPE_CAT_FK`
    FOREIGN KEY (`CATEGORY_ID` )
    REFERENCES MAT_TRAINING_APP.`CATEGORY` (`CATEGORY_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CODE_SYSTEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CODE_SYSTEM` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CODE_SYSTEM` (
  `CODE_SYSTEM_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NOT NULL ,
  `CATEGORY_ID` VARCHAR(32) NOT NULL ,
  PRIMARY KEY (`CODE_SYSTEM_ID`) ,
  INDEX `CODE_SYS_CAT_FK` (`CATEGORY_ID` ASC) ,
  CONSTRAINT `CODE_SYS_CAT_FK`
    FOREIGN KEY (`CATEGORY_ID` )
    REFERENCES MAT_TRAINING_APP.`CATEGORY` (`CATEGORY_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`LIST_OBJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`LIST_OBJECT` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`LIST_OBJECT` (
  `LIST_OBJECT_ID` VARCHAR(32) NOT NULL ,
  `VERSION` VARCHAR(255) NOT NULL DEFAULT '1.0' ,
  `NAME` VARCHAR(255) NOT NULL ,
  `STEWARD` VARCHAR(255) NULL ,
  `OID` VARCHAR(255) NOT NULL ,
  `RATIONALE` VARCHAR(2000) NULL ,
  `COMMENT` VARCHAR(2000) NULL ,
  `OBJECT_STATUS_ID` VARCHAR(32) NOT NULL ,
  `OBJECT_OWNER` VARCHAR(32) NOT NULL ,
  `CATEGORY_ID` VARCHAR(32) NOT NULL ,
  `CODE_SYS_VERSION` VARCHAR(255) NOT NULL ,
  `CODE_SYSTEM_ID` VARCHAR(32) NOT NULL ,
  `MEASURE_ID` VARCHAR(32) NULL ,
  PRIMARY KEY (`LIST_OBJECT_ID`) ,
  INDEX `LIST_OBJECT_STATUS_FK` (`OBJECT_STATUS_ID` ASC) ,
  INDEX `LIST_OBJECT_USER_FK` (`OBJECT_OWNER` ASC) ,
  INDEX `LIST_OBJECT_CAT_FK` (`CATEGORY_ID` ASC) ,
  INDEX `LIST_OBJECT_CODE_SYSTEM_FK` (`CODE_SYSTEM_ID` ASC) ,
  CONSTRAINT `LIST_OBJECT_CODE_SYSTEM_FK`
    FOREIGN KEY (`CODE_SYSTEM_ID` )
    REFERENCES MAT_TRAINING_APP.`CODE_SYSTEM` (`CODE_SYSTEM_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LIST_OBJECT_STEWARD_FK`
    FOREIGN KEY (`STEWARD` )
    REFERENCES MAT_TRAINING_APP.`STEWARD_ORG` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LIST_OBJECT_STATUS_FK`
    FOREIGN KEY (`OBJECT_STATUS_ID` )
    REFERENCES MAT_TRAINING_APP.`OBJECT_STATUS` (`OBJECT_STATUS_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LIST_OBJECT_USER_FK`
    FOREIGN KEY (`OBJECT_OWNER` )
    REFERENCES MAT_TRAINING_APP.`USER` (`USER_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LIST_OBJECT_CAT_FK`
    FOREIGN KEY (`CATEGORY_ID` )
    REFERENCES MAT_TRAINING_APP.`CATEGORY` (`CATEGORY_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LIST_OBJECT_MEASURE_FK`
    FOREIGN KEY (`MEASURE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)    
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`LIST_OBJECT_OID_GEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`LIST_OBJECT_OID_GEN` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`LIST_OBJECT_OID_GEN` (
  `LIST_OBJECT_OID_GEN_ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(`LIST_OBJECT_OID_GEN_ID`)
)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CODE_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CODE_LIST` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CODE_LIST` (
  `CODE_LIST_ID` VARCHAR(32) NOT NULL ,
  PRIMARY KEY (`CODE_LIST_ID`),
  INDEX `CODE_LIST_OBJECT_FK` (`CODE_LIST_ID` ASC) ,
  CONSTRAINT `CODE_LIST_OBJECT_FK`
    FOREIGN KEY (`CODE_LIST_ID` )
    REFERENCES MAT_TRAINING_APP.`LIST_OBJECT` (`LIST_OBJECT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CODE` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CODE` (
  `CODE_ID` VARCHAR(32) NOT NULL ,
  `CODE` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(1400) NOT NULL ,
  `CODE_LIST_ID` VARCHAR(32) NOT NULL ,
  PRIMARY KEY (`CODE_ID`) ,
  INDEX `CODE_LIST_FK` (`CODE_LIST_ID` ASC) ,
  CONSTRAINT `CODE_LIST_FK`
    FOREIGN KEY (`CODE_LIST_ID` )
    REFERENCES MAT_TRAINING_APP.`CODE_LIST` (`CODE_LIST_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`GROUPED_CODE_LISTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`GROUPED_CODE_LISTS` ;
CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`GROUPED_CODE_LISTS` (
  `GROUPED_CODE_LISTS_ID` VARCHAR(32) NOT NULL ,
  `GROUP_LIST_ID` VARCHAR(32) NOT NULL ,
  `CODE_LIST_ID` VARCHAR(32) NOT NULL ,
  `DESCRIPTION` VARCHAR(1000) NOT NULL ,
  PRIMARY KEY (`GROUPED_CODE_LISTS_ID`) ,
  INDEX `GR_CODE_LIST_FK` (`CODE_LIST_ID` ASC) ,
  INDEX `GR_LIST_OBJ_FK` (`GROUP_LIST_ID` ASC) ,
  CONSTRAINT `GR_CODE_LIST_FK`
    FOREIGN KEY (`CODE_LIST_ID` )
    REFERENCES MAT_TRAINING_APP.`CODE_LIST` (`CODE_LIST_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GR_LIST_OBJ_FK`
    FOREIGN KEY (`GROUP_LIST_ID` )
    REFERENCES MAT_TRAINING_APP.`LIST_OBJECT` (`LIST_OBJECT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- ----------- BEGIN MEASURE ---------------------------



-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`CONTEXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`CONTEXT` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`CONTEXT` (
  `CONTEXT_ID` VARCHAR(64) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`CONTEXT_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`OPERATOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`OPERATOR` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`OPERATOR` (
  `OPERATOR_ID` VARCHAR(64) NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `TYPE` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`OPERATOR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`STATIC_ELEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`STATIC_ELEMENT` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`STATIC_ELEMENT` (
  `STATIC_ELEMENT_ID` VARCHAR(64) NOT NULL ,
  `UNIT` VARCHAR(45) NOT NULL ,
  `QUANTITY` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`STATIC_ELEMENT_ID`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`TERM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`TERM` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`TERM` (
  `TERM_ID` VARCHAR(64) NOT NULL ,
  `ORDER` VARCHAR(45) NOT NULL ,
  `OPERATOR_ID` VARCHAR(64) NOT NULL ,
  `NEXT_TERM_ID` VARCHAR(64) NOT NULL ,
  `STATIC_ELEMENT_ID` VARCHAR(64) NOT NULL ,
  `QDS_ELEMENT_ID` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`TERM_ID`),
  INDEX `OPERATOR_ID_FK` (`OPERATOR_ID` ASC) ,
  INDEX `NEXT_TERM_ID_FK` (`NEXT_TERM_ID` ASC) ,
  INDEX `STATIC_ELEMENT_ID_FK` (`STATIC_ELEMENT_ID` ASC) ,
  INDEX `QDS_ELEMENT_ID_FK` (`QDS_ELEMENT_ID` ASC),
  CONSTRAINT `OPERATOR_ID_FK`
    FOREIGN KEY (`OPERATOR_ID` )
    REFERENCES MAT_TRAINING_APP.`OPERATOR` (`OPERATOR_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `NEXT_TERM_ID_FK`
    FOREIGN KEY (`NEXT_TERM_ID` )
    REFERENCES MAT_TRAINING_APP.`TERM` (`TERM_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `STATIC_ELEMENT_ID_FK`
    FOREIGN KEY (`STATIC_ELEMENT_ID` )
    REFERENCES MAT_TRAINING_APP.`STATIC_ELEMENT` (`STATIC_ELEMENT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `QDS_ELEMENT_ID_FK`
    FOREIGN KEY (`QDS_ELEMENT_ID` )
    REFERENCES MAT_TRAINING_APP.`QDS_ELEMENT` (`QDS_ELEMENT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QDS_ELEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QDS_ELEMENT` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QDS_ELEMENT` (
  `QDS_ELEMENT_ID` VARCHAR(64) NOT NULL ,
  `MEASURE_PACKAGE_ID` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`QDS_ELEMENT_ID`) ,
  INDEX `MEASURE_PACKAGE_ID_QDS_ELEMENT_FK` (`MEASURE_PACKAGE_ID` ASC) ,
  CONSTRAINT `MEASURE_PACKAGE_ID_QDS_ELEMENT_FK`
    FOREIGN KEY (`MEASURE_PACKAGE_ID` )
    REFERENCES MAT_TRAINING_APP.`MEASURE_PACKAGE` (`MEASURE_PACKAGE_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table MAT_TRAINING_APP.`QDS_PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS MAT_TRAINING_APP.`QDS_PROPERTY` ;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`QDS_PROPERTY` (
  `QDS_PROPERTY_ID` VARCHAR(64) NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `VALUE` VARCHAR(200) NOT NULL ,
  `TYPE` VARCHAR(45) NOT NULL ,
  `QDS_ELEMENT_ID` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`QDS_PROPERTY_ID`),
  INDEX `QDS_ELEMENT_ID_QDS_PROPERTY_FK` (`QDS_ELEMENT_ID` ASC) ,
  CONSTRAINT `QDS_ELEMENT_ID_QDS_PROPERTY_FK`
    FOREIGN KEY (`QDS_ELEMENT_ID` )
    REFERENCES MAT_TRAINING_APP.`QDS_ELEMENT` (`QDS_ELEMENT_ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS MAT_TRAINING_APP.`ATTRIBUTE_DETAILS` (
  `ATTRIBUTE_DETAILS_ID` VARCHAR(64) NOT NULL ,
  `ATTR_NAME` VARCHAR(200) NOT NULL ,
  `CODE` VARCHAR(200) NOT NULL ,
  `CODE_SYSTEM` VARCHAR(200) NOT NULL ,
  `CODE_SYSTEM_NAME` VARCHAR(200) NOT NULL ,
  `MODE` VARCHAR(200) NOT NULL ,
  `TYPE_CODE` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ATTRIBUTE_DETAILS_ID`))
ENGINE = InnoDB;


COMMIT;
-- ------------- END MEASURE ---------------------------
-- -----------------------------------------------------


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
